# Generated by Django 5.1.6 on 2025-03-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, verbose_name='Модель телефона')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('image', models.ImageField(default=None, upload_to='', verbose_name='Изображение')),
                ('release_date', models.DateField(default=None, verbose_name='Дата выпуска')),
                ('lte_exists', models.BooleanField(default=None, verbose_name='LTE')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
